const paragraphs = [
"The morning sun peeked over the horizon painting the sky in shades of gold and pink Birds sang in the distance while a gentle breeze rustled through the trees The air smelled fresh and invigorating encouraging people to start their day with energy and optimism ready to face new opportunities",
"In the heart of the city the streets were alive with movement and color Street vendors sold fresh produce while musicians played cheerful tunes People hurried along sidewalks yet moments of laughter and friendly greetings created warmth amidst the chaos Life here was vibrant fast paced and full of unexpected discoveries",
"A quiet forest path meandered between towering trees Sunlight filtered through the canopy creating dancing patterns on the forest floor Birds chirped overhead while a small brook babbled beside the trail The scent of moss and pine filled the air providing a peaceful retreat for those seeking solace in nature",
"The seaside village woke to the sound of crashing waves Fishermen prepared their boats and children played along the shore The salty breeze mingled with the aroma of freshly baked bread from local bakeries Colorful houses lined the cobbled streets offering a charming view and a welcoming atmosphere for visitors and residents alike",
"In the old library shelves of books reached toward the ceiling Sunlight streamed through large windows illuminating dust particles that danced in the air Students and readers sat quietly at wooden tables absorbed in stories and research The atmosphere was calm and contemplative a sanctuary for knowledge and imagination alike",
"A gentle rain fell over the countryside nourishing the green fields and gardens Farmers moved carefully through muddy paths while birds sought shelter under trees The scent of wet earth and blooming flowers filled the air creating a serene and refreshing ambiance Life seemed slower allowing appreciation for small beautiful details",
"The city park buzzed with activity as people jogged strolled and played Dogs ran freely chasing balls and each other while children laughed and screamed with joy Flowers bloomed in vibrant colors along the pathways The air smelled faintly of fresh grass and summer offering a lively escape from urban life",
"In the quiet cafe soft music played as patrons sipped coffee and read newspapers The aroma of freshly brewed drinks filled the space mingling with the scent of baked pastries Conversations were hushed punctuated by laughter and the clinking of cups It was a small haven where time moved more gently and pleasantly",
"The mountain trail wound through rugged terrain offering breathtaking views at every turn Pine trees lined the path their needles brushing against hikers' hands A clear stream ran nearby reflecting sunlight and creating tiny rainbows in the mist The air was crisp and invigorating encouraging travelers to push forward and explore further",
"On the sandy beach waves lapped at the shore rhythmically Children built sandcastles while seagulls circled above searching for scraps Colorful umbrellas dotted the coastline providing shade for families enjoying the sun The salty breeze carried laughter music and the occasional shout creating a lively yet relaxing atmosphere by the ocean",
"The marketplace buzzed with energy as vendors called out to potential customers Fresh fruits vegetables spices and handmade crafts filled the stalls People moved among the crowds chatting and laughing while examining the colorful offerings The smell of spices flowers and baked goods combined creating an intoxicating atmosphere of life and community",
"A small creek wound through the meadow its waters sparkling in the afternoon sun Wildflowers dotted the grassy banks swaying gently in the breeze Birds sang and insects buzzed in harmony completing a perfect natural symphony The peacefulness of the scene encouraged quiet reflection and a deep sense of calm for anyone nearby",
"The train station was bustling with passengers rushing to catch their departures Luggage trolleys rolled along the polished floors while announcements echoed overhead Some travelers lingered enjoying coffee and snacks while others hurried past The rhythm of movement sounds and smells created a vivid portrait of life in constant motion",
"In the quiet village smoke rose lazily from chimneys as families prepared meals Children ran along cobblestone streets their laughter mixing with the sounds of clattering pots and distant bells Flowers bloomed in window boxes adding color to charming houses The air smelled of bread herbs and fresh earth inviting contentment and ease",
"The evening sky blazed with orange and purple hues signaling the close of day Streetlights flickered on casting soft glows across the sidewalks People strolled leisurely enjoying the last moments of sunlight Shops closed one by one leaving only the quiet hum of the city and the occasional distant chatter of neighbors",
"A cozy cabin nestled in the forest emitted smoke from its chimney Inside a fire crackled warmly in the hearth while a cat purred on the rug Outside the wind rustled leaves gently creating a comforting rhythm The smell of wood and freshly baked bread made the cabin a welcoming retreat from the cold",
"The university campus bustled with students walking between buildings Laughter and conversations echoed across the green lawns Professors hurried along carrying books and papers Trees swayed in the breeze providing shade and a touch of nature amidst the busy academic environment Life on campus was vibrant energetic and full of purpose",
"Along the riverbank fishermen cast their lines hoping for a good catch Ducks swam nearby creating ripples in the water The sun reflected off the surface producing a sparkling effect The gentle sound of flowing water mixed with birdsong providing a soothing environment for those seeking relaxation or quiet reflection by the river",
"The theater lobby was alive with excitement as patrons gathered before the performance The smell of popcorn and perfume mingled creating a unique atmosphere People chatted enthusiastically sharing expectations and predictions for the show Lights dimmed and the audience slowly moved toward their seats eager for the drama and magic that awaited them on stage",
"In the desert the sun blazed overhead casting long shadows over sand dunes Wind sculpted patterns in the sand while a lone traveler moved steadily across the landscape Despite the harsh conditions the environment held a stark beauty The sky stretched endlessly its intense blue contrasting with golden sands creating a scene of quiet majesty",
"The bakery smelled of fresh bread and pastries drawing customers from the busy street Golden croissants and sweet rolls were arranged neatly on trays People chatted softly while enjoying morning coffee Outside the city woke to another day The warmth of the bakery provided comfort and a moment of calm amid urban rush",
"The snow covered landscape glistened under winter sunlight Pine branches bent under the weight of fresh powder creating natural archways along the path Animal tracks crisscrossed the pristine surface telling stories of nocturnal wanderings The air was crisp and cold carrying the clean scent of winter that invigorated the senses with each breath",
"The art gallery stood quiet and imposing white walls displaying vibrant works of creativity Visitors moved slowly from piece to piece some whispering observations others lost in silent contemplation Natural light from skylights illuminated brushstrokes and textures revealing the artists' intentions The space was a sanctuary for visual storytelling and emotional connection",
"The rooftop garden offered an escape from the urban landscape below Colorful containers held herbs vegetables and flowers creating a patchwork of life against the concrete backdrop Bees buzzed between blossoms while birds visited birdbaths The city's sounds softened here replaced by rustling leaves and the gentle hum of nature thriving in unexpected places",
"The fog rolled in from the sea blanketing the coastal town in mystery Streetlights cast hazy halos in the damp air and distant ship horns sounded mournful through the mist Footsteps echoed on wet pavement as figures moved like shadows through the obscured streets The world seemed suspended between reality and imagination in this ethereal atmosphere",
"The carnival grounds pulsed with excitement and sensory overload Bright lights flashed against the night sky as rides spun and tilted Laughter mingled with screams of delight and the tinny music of carousel organs The air smelled of popcorn cotton candy and fried dough Children ran with balloons while couples strolled hand in hand creating memories amid the chaos",
"The ancient ruins stood silhouetted against the setting sun weathered stones telling stories of civilizations long past Crumbling columns reached toward the sky like fingers of history Moss and wildflowers grew in crevices nature reclaiming what humans had built Visitors walked quietly among the remnants feeling the weight of time and the continuity of human experience",
"The ice skating rink glimmered under floodlights as figures twirled and glided across the frozen surface Cold air carried the sound of blades cutting ice and occasional laughter as someone stumbled Parents helped children find their balance while experienced skaters performed graceful turns Steam rose from hot chocolate cups at the rink's edge where spectators watched the winter dance",
"The hospital corridor was quiet during the night shift fluorescent lights humming overhead Nurses moved with practiced efficiency their soft soled shoes making little sound on polished floors Monitors beeped in rhythmic patterns from behind closed doors The air carried the antiseptic scent of cleanliness mixed with the faint aroma of coffee from the breakroom where staff found brief moments of respite",
"The rooftop bar buzzed with conversation as the city lights twinkled below Glasses clinked and ice swirled in cocktails while patrons leaned against the railing taking in the panoramic view A gentle breeze carried music from hidden speakers The bartender worked with practiced flair creating drinks that sparkled under string lights Above stars competed with the urban glow for attention",
"The autumn forest was ablaze with color as leaves turned from green to gold crimson and amber A crisp breeze sent them cascading to the forest floor creating a crunchy carpet underfoot Squirrels scurried about gathering nuts for the coming winter The air smelled of decay and renewal a natural cycle that promised spring's return even as nature prepared for sleep",
"The abandoned amusement park stood silent rides frozen in mid motion as if waiting for visitors who would never return Paint peeled from carousel horses and roller coaster tracks Weeds grew through cracks in the pavement slowly reclaiming the land Yet somehow echoes of laughter and joy seemed to linger in the air ghostly reminders of the happiness that once filled these spaces",
"The hot air balloon festival painted the dawn sky with vibrant colors Dozens of balloons inflated slowly their fabric canopies blossoming like flowers against the morning light Flames roared periodically sending the crafts ascending into the atmosphere Passengers looked down from their baskets watching the world shrink below On the ground spectators craned their necks cameras ready to capture the magical spectacle",
"The monastery garden was a place of perfect tranquility Monks in simple robes moved silently among vegetable plots and flower beds tending plants with gentle care Stone pathways meandered through the space leading to quiet benches for meditation The air was filled with birdsong and the rustle of leaves a natural symphony that complemented the spiritual atmosphere of this sacred place",
"The night market came alive as darkness fell stalls illuminated by strings of colorful lights Vendors called out offering everything from exotic foods to handmade crafts The air was thick with aromas of grilling meat spices and sweet desserts People moved through the narrow aisles sampling treats and haggling good naturedly Music from various stalls created a cacophony that somehow blended into an energetic harmony",
"The vineyard stretched across rolling hills rows of grapevines creating geometric patterns against the landscape Sunlight filtered through leaves ripening fruit that would soon become wine The air smelled of earth grapes and distant rain A stone farmhouse stood at the center its porch offering a perfect vantage point to watch the sunset cast golden light across the fields of future vintage",
"The underground subway station was a world of constant motion Trains arrived and departed with rushing air and screeching brakes People flowed up and down escalators their faces illuminated by digital advertisements Musicians played for coins in designated corners their music competing with announcements and the rumble of passing trains Despite the chaos there was an underlying rhythm to this urban underground ecosystem",
"The botanical greenhouse was a humid paradise filled with exotic plants from around the world Orchids bloomed in impossible colors while ferns unfurled their delicate fronds A small waterfall cascaded into a pond where koi fish swam lazily Visitors moved slowly along the paths occasionally stopping to read informational plaques or simply breathe in the oxygen rich air It was a jungle contained within glass and steel",
"The lighthouse stood firm against the rocky coast its beam cutting through the night fog at regular intervals Waves crashed against the cliffs below their spray reaching the white washed tower Inside spiral stairs led to the lantern room where the keeper maintained the light that guided ships to safety The building was both a warning and a promise a solitary guardian against the dangers of the sea",
"The ski resort buzzed with winter energy as people bundled in colorful gear moved between slopes and lodges The mountain was carved with trails of varying difficulty each dotted with tiny figures descending in controlled chaos The air was cold and crisp carrying the scent of pine and hot chocolate from the warming hut at the base Chairlifts rose steadily carrying adventurers to the summit for another run down the snow covered mountain",
"The flower market was a riot of color and fragrance Stalls overflowed with blooms of every variety from common daisies to exotic orchids Florists arranged bouquets with artistic precision while customers chose flowers for every occasion The air was thick with perfume a natural aromatherapy that lifted spirits Early morning light illuminated petals making dewdrops sparkle like tiny jewels on the vibrant displays",
"The observatory dome opened to reveal the night sky stars scattered across darkness like diamonds on velvet The powerful telescope brought distant galaxies into view their light traveling millions of years to reach this moment Visitors took turns peering into the eyepiece gasping at celestial wonders An astronomer pointed out constellations sharing ancient stories that humans have told while looking up at these same stars for millennia",
"The fishing harbor was active before dawn as boats returned with their night's catch Seagulls circled overhead their cries mixing with the rumble of diesel engines and the splash of water against hulls Fishermen moved with practiced efficiency sorting and storing their haul The air was thick with the smell of salt and fish a scent that signaled both hard work and sustenance for the coastal community",
"The rooftop greenhouse was an urban oasis glass walls protecting plants from the city below Tomatoes ripened on vines while herbs grew in neat rows Bees buzzed between flowers pollinating with purpose The gardener moved carefully among the plants checking moisture levels and pruning as needed From this elevated garden the city looked like a distant abstract painting while life flourished in this contained environment",
"The antique shop was a treasure trove of forgotten stories Dust motes danced in shafts of light that illuminated glass cases and crowded shelves Each item held history a tarnished silver locket a yellowed book with marginalia a porcelain doll with a chipped cheek The shopkeeper knew the provenance of many pieces sharing tales of previous owners with curious customers who appreciated objects with pasts",
"The ice cream parlor was a colorful haven of sweet treats Glass cases displayed dozens of flavors in pastel hues from classic vanilla to exotic combinations Children pressed their faces against the glass while parents deliberated choices The air was cold and sweet carrying the scent of waffle cones and sugar Behind the counter staff scooped generous portions adding sprinkles and sauces to create perfect desserts for happy customers",
"The campsite was nestled in a forest clearing tents arranged in a circle around a central fire pit Campers moved between activities some preparing food others setting up hammocks or organizing gear The smell of woodsmoke and coffee mingled with pine scents As evening approached the fire was lit its flames dancing and casting flickering light on faces gathered to share stories and enjoy the simplicity of outdoor living",
"The rooftop yoga class began as the sun rose over the city skyline Mats were arranged in neat rows on the wooden deck participants facing east to greet the day The instructor's voice was calm and guiding leading through poses that stretched and strengthened Below the city was coming to life but up here there was only the sound of breathing gentle movement and distant traffic creating a peaceful urban meditation",
"The science museum buzzed with excited children and curious adults Interactive displays invited hands on exploration of principles from physics to biology A massive dinosaur skeleton dominated the main hall its bones telling stories of ancient life In the planetarium visitors leaned back in reclining seats as stars filled the dome above The air was filled with sounds of discovery gasps of wonder questions and explanations that made complex concepts accessible and fun",
"The winter market was a magical gathering in the town square Wooden stalls sold handmade gifts warm clothing and seasonal treats The air was cold but filled with the aroma of mulled wine roasted nuts and evergreen boughs People moved between vendors their breath visible in the frosty air A small choir sang carols while children rode a miniature carousel The entire scene was illuminated by twinkling lights and the soft glow of lanterns",
"The artist's studio was a controlled chaos of creativity Canvases in various stages of completion leaned against walls while brushes soaked in jars of turpentine Tubes of paint were squeezed and arranged on a wooden palette Natural light from a large window illuminated the space where inspiration transformed into visual expression The air smelled of linseed oil and clay a scent that signaled the birth of new artistic visions",
"The community garden was a patchwork of individual plots each reflecting the personality of its gardener Some grew neat rows of vegetables others cultivated wildflowers and a few created elaborate landscapes with paths and water features Gardeners exchanged tips and seeds over low fences sharing knowledge and harvests The space was more than just a place to grow food it was where neighbors became friends and the concrete jungle gave way to green community",,
"The rooftop skate park was an unexpected urban oasis ramps and rails arranged against a backdrop of city skyline Skateboards rolled across concrete with a distinctive rhythm occasionally punctuated by the sound of a trick successfully landed or a fall that brought laughter rather than tears The setting sun cast long shadows across the park creating an ever changing landscape of light and movement that inspired riders to push their limits in this elevated playground",
"The night market was a feast for the senses food stalls sizzling with exotic dishes while vendors called out their specials Colorful lanterns illuminated crowds moving between stalls their conversations creating a constant hum of activity Musicians played traditional instruments on small stages their melodies weaving through the market like auditory threads The air was thick with aromas of spices grilled meats and sweet desserts creating an intoxicating atmosphere that celebrated culture and community",
"The greenhouse laboratory was a sterile environment where scientific precision met natural growth Researchers in white coats moved between rows of experimental plants recording data and adjusting conditions Specialized lighting mimicked various natural environments while sensors monitored every aspect of plant development Here in this controlled ecosystem scientists worked to solve agricultural challenges develop new varieties and unlock the secrets of plant biology that might help feed a growing world",
"The riverside cafe was perfectly positioned to watch the water flow by Outdoor tables offered views of passing boats while inside large windows framed the changing light on the water's surface Patrons sipped drinks and worked on laptops or chatted with friends The menu featured local ingredients with herbs grown in planters along the railing As evening approached strings of lights created a warm glow that reflected on the river transforming the space into a magical waterfront retreat",
"The rooftop apiary was an unexpected sanctuary in the heart of the city Beehives lined the perimeter of the green roof their inhabitants buzzing between flowers and returning laden with pollen The beekeeper moved carefully among the hives checking on the colonies and explaining the importance of urban pollination to visitors From this elevated garden the city seemed distant its sounds muted by the gentle hum of thousands of bees working together in perfect harmony to create honey and sustain plant life",
"The meditation center was a place of profound quiet its minimalist design encouraging inward focus Soft natural light filtered through sheer curtains illuminating cushions arranged in neat rows on polished wood floors The air was still and cool carrying a subtle scent of sandalwood from incense burned earlier Participants sat with eyes closed their breathing creating a gentle rhythm that unified the space Outside the world continued its busy pace but here time seemed to slow allowing for deep reflection and peace",
"The underground music venue was intimate and raw brick walls covered with posters from countless previous shows The stage was small but powerful its spotlight cutting through dim light and haze As the band began to play the room filled with sound that was both deafening and precise The crowd moved as one bodies swaying to rhythms that seemed to pulse through the floor Sweat and adrenaline created an electric atmosphere where music became a physical force connecting everyone present",
"The rooftop farm was a testament to urban innovation raised beds and hydroponic systems transforming empty space into productive land Vegetables grew in neat rows while fruit vines climbed trellises The farmer moved between plants checking for pests and harvesting ripe produce A small compost bin turned waste from the building below into nutrient rich soil From this elevated position the city seemed both overwhelming and manageable a reminder that growth and nourishment could happen anywhere with creativity and care",
"The lakeside cabin was a perfect retreat from modern life its wooden porch offering panoramic views of water and mountains A small dock extended into the clear lake a canoe tied to its side waiting for exploration Inside the space was cozy but uncluttered with comfortable furniture and large windows that framed nature like living paintings The air smelled of woodsmoke from the stone fireplace and pine from the surrounding forest creating an atmosphere of peaceful isolation where time seemed to slow to the rhythm of waves lapping the shore",
"The community kitchen was a place of cultural exchange and culinary education Multiple cooking stations allowed different groups to prepare traditional foods simultaneously The air was a complex tapestry of aromas spices herbs baking bread and sizzling vegetables Participants shared techniques and stories as they worked their movements creating a choreographed dance around the room At the end of class everyone gathered around large tables to share the meal they had created together their differences celebrated through the universal language of food",
"The rooftop observatory offered a unique perspective on both the city and the cosmos A powerful telescope pointed toward the heavens its lens bringing distant celestial objects into stunning clarity The astronomer guided visitors through constellations planets and nebulae sharing stories that connected ancient mythology with modern science Below the city lights created a glittering carpet that seemed to mirror the stars above In this elevated space between earth and sky the universe felt both infinitely vast and surprisingly accessible",
"The underground art gallery was a hidden gem its converted industrial space providing the perfect backdrop for contemporary works Exposed brick walls and high ceilings created an atmosphere of urban sophistication Track lighting illuminated paintings and sculptures that challenged conventional thinking Visitors moved slowly through the space sometimes pausing to read artist statements or discuss interpretations with companions The basement location created a sense of discovery as if those who found this place were part of an exclusive club of art enthusiasts",
"The rooftop classroom was an innovative educational space where learning met the environment Students sat at desks arranged to face outward with the city as their backdrop Lessons often incorporated the surroundings weather patterns visible in the sky architectural styles below or ecosystems thriving in planters along the perimeter The teacher moved between students the natural light illuminating materials and engaged faces This elevated learning environment reminded everyone that education wasn't confined to buildings but connected to the wider world",
"The community workshop was a space where ideas became tangible through tools and collaboration Workbenches were arranged with equipment for woodworking metalworking electronics and textile arts Members moved between projects sometimes offering advice or assistance to others The air smelled of sawdust solder and creativity Completed projects lined shelves furniture art pieces inventions and repairs This shared space democratized making allowing people with diverse skills and backgrounds to learn from each other and bring their visions to life",
"The rooftop theater was an unexpected venue where performances met the skyline A simple stage was set against a backdrop of city lights with seating arranged to take advantage of the urban panorama As actors performed the city became part of the set its rhythms and lights complementing the theatrical experience Audience members wrapped in blankets against the evening chill were transported by stories while remaining connected to the urban environment This elevated stage created a magical intersection of human creativity and the architectural beauty of the city below",
"The underground hydroponic farm was a futuristic vision of agriculture its LED lights casting a purple glow on rows of plants growing without soil Nutrient rich water circulated through the system delivering precisely what each plant needed Workers moved between aisles monitoring growth and harvesting produce that would travel just blocks to restaurants and markets above This subterranean garden represented a new approach to urban food production where technology and nature combined to create sustainable solutions for feeding cities",
"The rooftop wildlife sanctuary was an unexpected haven in the urban landscape Native plants provided food and shelter for birds butterflies and beneficial insects Small water features offered drinking spots and birdbaths The naturalist who maintained the space kept careful records of species that visited noting how this elevated ecosystem connected to larger migration patterns From this perch visitors could observe nature's resilience and adaptation a reminder that wildlife could thrive even in the most developed environments when given the opportunity",
"The community recording studio was a place where musical dreams became reality Soundproofed rooms contained equipment for every step of the creative process from writing to mixing Musicians of all genres and skill levels collaborated their diverse backgrounds creating unique sounds The air hummed with potential and the energy of creativity Local producers volunteered their expertise helping artists capture their vision This shared space democratized music production allowing voices that might otherwise go unheard to find expression and audience",
"The rooftop sculpture garden was an open air museum where art met sky Pieces in various materials and styles were arranged to take advantage of changing light and weather conditions Some works incorporated natural elements responding to wind and rain Visitors moved slowly through the space viewing art from multiple angles against the backdrop of city and sky The elevated location created a sense of discovery as if these creative expressions were meant to be found above the urban chaos in a space where imagination could soar",
"The underground gaming lounge was a retreat for digital adventurers its low lighting and comfortable stations creating an immersive environment Multiple screens glowed with different virtual worlds while players wore headsets that connected them to teammates and opponents The air was filled with the sounds of clicking controllers occasional exclamations and the hum of high performance computers This subterranean space was a modern community center where friendships formed across digital landscapes and pixels and code created connections that transcended physical boundaries",
"The rooftop dance studio was a place where movement met the horizon Mirrors reflected dancers against a backdrop of sky and cityscape The sprung floor provided perfect support for leaps and turns while the open air offered natural ventilation and inspiration Classes ranged from ballet to hip hop students learning techniques while enjoying the unique perspective of dancing above the urban landscape As the sun set the space transformed with golden light creating an ethereal atmosphere where art and environment merged in perfect harmony",
"The community repair cafe was a space where broken things found new life Tables were organized by specialty electronics clothing furniture bicycles with tools and volunteers ready to assist People brought items they might otherwise discard learning to fix them with guidance The air buzzed with the sounds of repair sewing machines soldering irons and the satisfying click of parts fitting back together This gathering place challenged throwaway culture valuing sustainability skill sharing and the quiet satisfaction of making things whole again",
"The rooftop writing retreat offered writers a space elevated above daily distractions Simple desks were arranged to face outward with views that inspired rather than interrupted Some writers typed furiously while others stared into the distance ideas taking shape in their minds The air was quiet but for the rustle of pages and the occasional sigh of frustration or discovery This elevated space reminded storytellers that perspective was everything that sometimes the clearest view came from distance both physical and emotional",
"The underground speakeasy was a step back in time its dim lighting and jazz music creating an atmosphere of clandestine sophistication Bartenders in period attire mixed classic cocktails with practiced flair their movements precise and theatrical Patrons dressed for the occasion their conversations creating a low murmur beneath the music The subterranean location added to the sense of discovery as if visitors had been let in on a secret that existed just beneath the surface of the modern city a portal to another era",
"The rooftop wellness center was a sanctuary for mind and body elevated above urban stress Yoga mats were arranged for morning practice as the sun rose over the skyline Meditation cushions offered a place for quiet reflection with panoramic views Treatment rooms provided massage and therapy with natural light and fresh air The space incorporated elements of nature plants water features and natural materials creating an environment where healing could begin From this perch the city's challenges seemed more manageable reminding visitors that perspective and peace were always within reach",
"The community makerspace was a workshop of infinite possibilities its tools and equipment available to members with diverse interests and skills 3D printers whirred beside traditional woodworking tools while laser cutters etched designs into various materials People moved between projects sometimes collaborating sometimes working independently but always with the potential for shared knowledge The air smelled of creativity sawdust solder and innovation This shared space democratized making allowing ideas to become reality through access education and community support",
"The rooftop cinema was an enchanting venue where films met the stars Comfortable seating was arranged with blankets and pillows for cozy viewing As dusk fell the screen came to life against a backdrop of city lights and actual stars above The sound system carried dialogue and music through the night air while viewers were wrapped in the magic of storytelling under the open sky This elevated theater experience created a sense of community among strangers all sharing in the timeless joy of cinema in an unforgettable setting",
"The underground library was a quiet refuge beneath the city bustle its shelves carved from earth and stone Soft lighting illuminated reading nooks where visitors escaped into other worlds through books The air was cool and still carrying the distinctive scent of paper and knowledge that has existed for centuries This subterranean sanctuary offered a different kind of depth not just below ground but into imagination history and human experience Here in this quiet space the constant motion of the city above seemed distant and unimportant",
"The rooftop beekeeping sanctuary was an unexpected intersection of nature and urban life Hives were carefully arranged to maximize sun exposure while minimizing wind The beekeeper moved with practiced calm among the colonies explaining the importance of pollinators to visitors Honey extracted on site was sold in small jars each batch reflecting the seasonal flowers available in the city From this elevated apiary the urban landscape transformed into a diverse ecosystem where bees and humans coexisted creating sweetness in more ways than one",
"The community art studio was a space where creative expression was accessible to all Easels stood ready for painters pottery wheels awaited sculptors and printing presses offered possibilities for graphic artists The air was filled with the energy of creation the scent of clay turpentine and possibility People of all skill levels worked side by side sometimes collaborating sometimes pursuing individual visions This shared space democratized art making proving that creativity wasn't reserved for the gifted but was a human impulse that flourished with opportunity and encouragement",
"The rooftop astronomy club gathered weekly to explore the cosmos from their urban perch Telescopes of various sizes were arranged to point toward different celestial objects The amateur astronomer who led the group shared knowledge with enthusiasm pointing out constellations planets and deep sky objects The city lights below created a strange contrast to the darkness of space they observed In this elevated space between earth and sky members found perspective and wonder their urban concerns dwarfed by the vastness of the universe above",
"The underground fermentation lab was a place where science met culinary tradition Glass vessels held bubbling concoctions at various stages kombucha kefir kimchi and more The air was thick with distinctive sour smells that signaled beneficial bacteria at work Researchers in lab coats monitored temperature and pH levels while also tasting the developing flavors This subterranean space was dedicated to preserving ancient food preservation techniques while applying modern scientific understanding creating products that were both delicious and beneficial for health",
"The rooftop music conservatory offered a unique learning environment where students practiced against the sky Soundproof practice rooms allowed for focused work while common areas encouraged collaboration The acoustics were designed to work with the open air creating exceptional performance spaces Students of various instruments moved between lessons and practice their music sometimes drifting across the rooftop This elevated musical education reminded students that art was both personal and universal that their notes could rise above the urban noise to touch something transcendent",
"The mountain cabin stood blanketed in pristine snow smoke curling from its stone chimney Inside a fire crackled while skis rested by the door Ice crystals decorated windowpanes creating intricate patterns that transformed sunlight into rainbows The silence was profound broken only by the whisper of wind through pine branches and occasional distant avalanche",
"The airport terminal hummed with perpetual motion travelers rushing to gates while announcements echoed overhead Suitcases rolled across polished floors as children pointed at planes through massive windows The air smelled of coffee cleaning products and anticipation Departures and arrivals created an emotional tapestry of hellos and goodbyes against a backdrop of constant movement",
"The bookstore closed for the night leaving only the soft glow of security lights Dust motes danced in moonbeams that slanted through high windows The scent of aging paper and leather bindings created an atmosphere of quiet wisdom Books stood like silent sentinels their stories waiting for tomorrow's readers to unlock their secrets",
"The desert oasis shimmered like a mirage as sunset painted the sand in gold and crimson Palm fronds rustled in the cooling breeze while water reflected the changing sky Date palms offered shade to weary travelers who gathered around the spring The air smelled of dust water and the sweet promise of rest",
"The farmers market buzzed with morning energy as vendors arranged colorful produce in neat rows Tomatoes glistened in sunlight while fresh herbs released their fragrances Customers chatted with growers exchanging recipes and stories The air was thick with the smells of earth ripe fruit and freshly baked bread creating a celebration of local harvest",
"The riverside picnic spot was a perfect summer sanctuary Blankets dotted the grassy bank while children splashed in shallow water A gentle breeze carried the scent of wildflowers and sunscreen Laughter mingled with the sound of water flowing over smooth stones As afternoon waned golden light filtered through trees creating an idyllic scene of simple pleasures",
"The old movie theater was a palace of memories its velvet curtains faded but still majestic Popcorn butter scent lingered in the air decades after the last showing Dust motes danced in projector beams that never again illuminated the screen The seats stood empty waiting for audiences that would never return yet somehow still echoing with laughter and gasps from films long past",
"The rooftop garden party glowed under string lights as guests mingled among container plants The city skyline created a dramatic backdrop as cocktails clinked and soft music played A breeze carried the scent of jasmine and conversation Below traffic moved like glowing rivers while above stars competed with urban glow creating a magical evening suspended between earth and sky",
"The foggy morning transformed the countryside into an ethereal landscape Trees emerged like ghosts from the mist while familiar paths became mysterious adventures Bird calls sounded muffled and distant Dewdrops clung to spiderwebs creating delicate necklaces of light As the sun slowly burned through the gray veil the world reappeared washed clean and renewed",
"The hospital emergency room pulsed with controlled chaos Doctors and nurses moved with practiced efficiency through corridors filled with urgency Monitors beeped in rhythmic patterns while families waited anxiously The air smelled of antiseptic and coffee a strange combination of science and humanity Despite the tension there was an underlying rhythm of healing and hope that permeated the space",
"The lakeside campfire drew people together as darkness fell Flames danced casting flickering light on faces and creating shadows beyond the circle The scent of woodsmoke mingled with marshmallow roasting on sticks Stories and laughter rose with sparks into the starry sky Across the water a loon called its haunting melody completing the perfect summer evening",
"The snow covered village street looked like a Christmas card come to life Lampposts cast warm halos on pristine white while smoke curled from chimneys Footsteps created a path through the otherwise untouched snow The air was crisp and cold carrying the scent of woodsmoke and distant baking Inside warmly lit homes families gathered creating a scene of perfect winter contentment",
"The tropical beach at sunrise offered a moment of pure magic The sky transformed from deep purple to brilliant orange as the first rays touched the water Palm fronds silhouetted against the changing light while gentle waves lapped the shore The air smelled of salt and possibility Early risers walked along the water's edge their footprints soon erased by the incoming tide",
"The old fashioned candy shop was a sweet wonderland of glass jars and colorful treats The air was thick with sugar and chocolate scents that transported visitors to childhood Wooden floors creaked underfoot as customers examined handmade confections The owner with her flour dusted apron and warm smile knew every customer by name and their favorite candy by heart",
"The university lecture hall filled with the quiet energy of learning Sunlight streamed through tall windows as students found their seats The professor arranged notes at the podium while anticipation built The air smelled of old books coffee and intellectual curiosity As the lecture began a collective focus settled over the room minds opening to new ideas and perspectives",
"The subway car during rush hour was a study in controlled intimacy Strangers stood shoulder to shoulder each lost in their own world while physically connected to others The train rocked rhythmically as it sped through dark tunnels Heads nodded to music only the wearer could hear At each stop a choreographed exchange of passengers occurred a brief moment of movement in the underground journey",
"The botanical garden in spring was a celebration of renewal Cherry blossoms created pink canopies overhead while tulips painted the ground in vibrant colors The air was thick with fragrances from thousands of blooming flowers Bees buzzed contentedly between blossoms while visitors moved slowly along paths cameras ready to capture nature's artistry Each corner revealed a new delight a perfect composition of color and form",
"The fishing boat rocked gently on the open ocean surrounded by endless blue The morning sun sparkled on water as the crew prepared their nets Seagulls circled overhead hoping for a catch The air smelled of salt and diesel a scent that signaled both hard work and freedom Far from shore with only horizon in every direction the small vessel seemed both vulnerable and capable",
"The rooftop bar at night offered an urban escape with panoramic views Glasses clinked as conversations flowed against the backdrop of city lights A gentle breeze carried music and laughter The bartender worked with practiced efficiency creating cocktails that sparkled under string lights Below traffic moved like glowing rivers while above stars competed with the urban glow creating a perfect moment suspended between earth and sky",
"The quiet monastery courtyard was a sanctuary of peace and contemplation Stone pathways meandered through carefully tended gardens A single fountain provided the only sound its gentle water music creating a meditative rhythm Monks in simple robes moved silently their presence adding to the atmosphere of tranquility The air smelled of incense old stone and blooming flowers creating a space where time seemed to slow to a meditative pace",
]

const paraContainer = document.querySelector('.para');
const resetBtn = document.getElementById('resetBtn');
const inputField = document.getElementById('typingInput');
const results = document.querySelector('.result');

let charSpans = [];
let currentParaWords = [];

// Generate random paragraph
function generateRandomPara() {
  paraContainer.innerHTML = '';
  inputField.value = '';
  results.textContent = '';

  const randomIndex = Math.floor(Math.random() * paragraphs.length);
  const para = paragraphs[randomIndex];

  currentParaWords = para.split(' '); // For word counting

  charSpans = [];

  const words = para.split(' ');

  words.forEach((word) => {
    const wordSpan = document.createElement('span');

    word.split('').forEach((char) => {
      const charSpan = document.createElement('span');
      charSpan.textContent = char;
      charSpan.classList.add('pending');
      wordSpan.appendChild(charSpan);
      charSpans.push(charSpan);
    });

    // Add space after each word
    const spaceSpan = document.createElement('span');
    spaceSpan.textContent = ' ';
    spaceSpan.classList.add('pending');
    wordSpan.appendChild(spaceSpan);
    charSpans.push(spaceSpan);

    paraContainer.appendChild(wordSpan);
  });
}

// Live character comparison
inputField.addEventListener('input', () => {
  const userChars = inputField.value.split('');

  charSpans.forEach((span, idx) => {
    if (!userChars[idx]) {
      span.className = 'pending';
    } else if (userChars[idx] === span.textContent) {
      span.className = 'correct';
    } else {
      span.className = 'wrong';
    }
  });
});

// Show results on Enter
inputField.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') {
    const inputWords = inputField.value.trim().split(/\s+/);

    let correctWords = 0;
    let incorrectWords = 0;

    currentParaWords.forEach((word, idx) => {
      if (inputWords[idx] === word) {
        correctWords += 1;
      } else {
        incorrectWords += 1;
      }
    });

    results.textContent = `Correct Words: ${correctWords} | Incorrect Words: ${incorrectWords} | Total Words: ${currentParaWords.length}`;
  }
});

// Reset paragraph
resetBtn.addEventListener('click', generateRandomPara);

// Initialize first paragraph
generateRandomPara();